# Generated by Django 3.1 on 2020-08-16 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unchockapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='checkin',
            unique_together={('booking_ref_num', 'passenger_first_name', 'passenger_last_name')},
        ),
        migrations.RemoveField(
            model_name='checkin',
            name='airline',
        ),
    ]
