# Generated by Django 3.1 on 2020-08-16 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('unchockapi', '0002_auto_20200816_1939'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='checkin',
            unique_together={('booking_ref_num', 'passenger_first_name', 'passenger_last_name', 'departure_date')},
        ),
    ]
