version: "3"

services:
  backend:
    container_name: api
    build: backend
    command: python manage.py runserver 0.0.0.0:80
    volumes:
      - ./backend:/code
    ports:
      - "80:80"
    depends_on:
      - db
  db:
    container_name: db
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
